sudo: require

os: linux

language: generic

dist: xenial

services:
  - docker

before_install:
  - echo "start creating on image with dockerfile"
  - docker build -t song22861/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true song22861/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-719823691862"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
